package fintech.evolution.variable.constants.user;

public interface UserStep {
    String STEP_START = "STEP_START";

    String STEP_SELECTED_LANG = "STEP_SELECT_LANG";
    String STEP_SETTINGS = "STEP_SELECT_LANG";
    String STEP_REGISTRATION = "STEP_REGISTRATION";
    String STEP_SET_NAME = "STEP_SET_NAME";
    String STEP_SET_SURNAME = "STEP_SET_SURNAME";
    String STEP_SET_PHONE = "STEP_SET_PHONE";
    String STEP_REVIEW = "STEP_REVIEW";
    String STEP_COOPERATION_FULL_NAME = "STEP_COOPERATION_FULL_NAME";
    String STEP_COOPERATION_PHONE = "STEP_COOPERATION_PHONE";
    String STEP_STATICS = "STEP_COOPERATION_SEND_PHOTO_OR_VIDEO";

    String STEP_SET_REGION = "STEP_SET_REGION";
    String STEP_SET_SUBJECT_NAME = "STEP_SET_SUBJECT_NAME";
    String STEP_SET_DISTRICT = "STEP_SET_DISTRICT";
    String STEP_SET_STIR = "STEP_SET_STIR";
    String STEP_SET_TYPE = "STEP_SET_TYPE";
    String STEP_SET_PRODUCT_NAME = "STEP_SET_PRODUCT_NAME";
    String STEP_SET_EMAIL = "STEP_SET_EMAIL";
    String STEP_SET_ACTIVITY_YEAR = "STEP_SET_ACTIVITY_YEAR";
    String STEP_SET_OPERATOR_NAME = "STEP_SET_OPERATOR_NAME";
    String STEP_SET_DATE = "STEP_SET_DATE";
    String STEP_SET_ADDRESS = "STEP_SET_ADDRESS";
    String STEP_SET_FINISH = "STEP_SET_FINISH";
}
